### ISSUE TITLE
Broken sed '/*/p'

### ISSUE THREAD

**Issue by jwilk** [wader/catgolf#23]
In #1, @Doctor-love added
```sh
sed '/*/p' file.txt
```
But this duplicates lines containing the `*` character. E.g.:

```console
$ printf '*hello*\nworld!\n' > file.txt
$ cat file.txt
*hello*
world!
$ sed '/*/p' file.txt
*hello*
*hello*
world!
```
There's now another sed call that is shorter and works correctly, so IMHO this one should be removed.

**Comment by magisterquis** [comment]
With BSD sed, at least, `sed '' file.txt` works as well.

**Comment by Doctor-love** [comment]
Agree!
