### ISSUE TITLE
Clarify rules

### ISSUE THREAD

**Issue by reftel** [wader/catgolf#57]
The rules are a bit unclear to me. Are non-pipe sequences of two commands allowed (as in `foo file.txt; bar`)? If so, I have one.

**Comment by wader** [comment]
Hey! haven't given much thought into it :) maybe pipe league should be renamed to shell features league etc?

@jwilk what do you think?

**Comment by alokmenghrajani** [comment]
+1 for renaming pipe league. Some of the current entries aren't even strictly pipes.

I would add a rule stating submissions to Brittle and Junk leagues need to explain the failure case.

**Comment by xyproto** [comment]
Also, junk league entries are mostly either brittle or output error messages in addition to content output.

I support renaming "pipe league" to "shell league" or something similar.

Finding the perfect categories, names and rules is hard! 🙂
